# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-23 21:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_caruselinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CaruselInfo',
        ),
    ]
