# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-23 21:14
from __future__ import unicode_literals

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_caruselinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaruselInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to=app.models.image_folder)),
                ('slug', models.SlugField()),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
