# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-24 21:08
from __future__ import unicode_literals

import app.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_caruselinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique_for_date='posted', verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Краткое содержание')),
                ('content', models.TextField(verbose_name='Полное содержание')),
                ('posted', models.DateTimeField(db_index=True, default=datetime.datetime(2019, 7, 25, 0, 8, 57, 285357), verbose_name='Опубликована')),
                ('image', models.ImageField(upload_to=app.models.image_folder, verbose_name='Путь к картинке')),
                ('slug', models.SlugField()),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
